[features]
resolution = true
skip-lint = false

[programs.mainnet]
mm_wallet_v2 = "4ZzKbBw9o1CuVgGVokLNWsgHy9Acnd4EzVH5N6nnbyf5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "C:/Users/salva/Downloads/whistle/playground-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

